name: Build and test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make

    - name: Unit tests
      run: make unit-tests

    - name: Integration tests
      run: make integration-tests

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: lisst
        path: lisst
