name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make

    - name: Unit tests
      run: make unit-tests

    - name: Integration tests
      run: make integration-tests

    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
          artifacts: lisst
          makeLatest: true
