name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make

    - name: Unit tests
      run: make unit-tests

    - name: Integration tests
      run: make integration-tests

    - name: Build amd64
      env:
        GOOS: linux
        GOARCH: amd64
      run: make clean && make && tar -cvf lisst-x86-64.tar lisst

    - name: Build arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: make clean && make && tar -cvf lisst-arm64.tar lisst

    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
          artifacts: lisst-*.tar
          makeLatest: true
          omitBody: true
